version: '3.8' 

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE 
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  ping:
    build: ./ping 
    environment:
      KAFKA_BROKER: kafka:9092
    depends_on:
      - kafka

  pong:
    build: ./pong 
    environment:
      KAFKA_BROKER: kafka:9092
    depends_on:
      - kafka
